#!/usr/bin/bash

image=$(mktemp --suffix=.png)

grim "$image"

convert "$image" -filter Gaussian \
    -resize 20% \
    -define "filter:sigma=1.5" \
    -resize 500.5% \
    -gravity center \
    "$image"

swaylock -i "$image"

rm $image
